//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 JsonData实例不属于Object类型. 的本地化字符串。
        /// </summary>
        internal static string Exception001 {
            get {
                return ResourceManager.GetString("Exception001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是一种有效的Json格式. 的本地化字符串。
        /// </summary>
        internal static string Exception002 {
            get {
                return ResourceManager.GetString("Exception002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议错误. 的本地化字符串。
        /// </summary>
        internal static string Exception003 {
            get {
                return ResourceManager.GetString("Exception003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码不匹配。 的本地化字符串。
        /// </summary>
        internal static string Exception004 {
            get {
                return ResourceManager.GetString("Exception004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该命令不存在。 的本地化字符串。
        /// </summary>
        internal static string Exception005 {
            get {
                return ResourceManager.GetString("Exception005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos;属性是无效的。 的本地化字符串。
        /// </summary>
        internal static string Exception006 {
            get {
                return ResourceManager.GetString("Exception006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Entermate用户验证失败。 的本地化字符串。
        /// </summary>
        internal static string Exception007 {
            get {
                return ResourceManager.GetString("Exception007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户注册失败。 的本地化字符串。
        /// </summary>
        internal static string Exception008 {
            get {
                return ResourceManager.GetString("Exception008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 企业用户注册失败。 的本地化字符串。
        /// </summary>
        internal static string Exception009 {
            get {
                return ResourceManager.GetString("Exception009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索用户信息失败。 的本地化字符串。
        /// </summary>
        internal static string Exception010 {
            get {
                return ResourceManager.GetString("Exception010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册为Facebook用户失败。 的本地化字符串。
        /// </summary>
        internal static string Exception011 {
            get {
                return ResourceManager.GetString("Exception011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册为谷歌用户失败。 的本地化字符串。
        /// </summary>
        internal static string Exception012 {
            get {
                return ResourceManager.GetString("Exception012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访客用户注册失败。 的本地化字符串。
        /// </summary>
        internal static string Exception013 {
            get {
                return ResourceManager.GetString("Exception013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成元数据失败。 的本地化字符串。
        /// </summary>
        internal static string Exception014 {
            get {
                return ResourceManager.GetString("Exception014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LoginLog注册失败。 的本地化字符串。
        /// </summary>
        internal static string Exception015 {
            get {
                return ResourceManager.GetString("Exception015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户修改（登录）失败。 的本地化字符串。
        /// </summary>
        internal static string Exception016 {
            get {
                return ResourceManager.GetString("Exception016", resourceCulture);
            }
        }
    }
}
