//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResLang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCHfD_cs_txt_05 {
            get {
                return ResourceManager.GetString("ACCHfD_cs_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCHfD_cs_txt_06 {
            get {
                return ResourceManager.GetString("ACCHfD_cs_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이름을 입력해주세요. 的本地化字符串。
        /// </summary>
        internal static string ACCHINFO_cs_txt_06 {
            get {
                return ResourceManager.GetString("ACCHINFO_cs_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업성공 的本地化字符串。
        /// </summary>
        internal static string ACCHRE_cs_mbox_02 {
            get {
                return ResourceManager.GetString("ACCHRE_cs_mbox_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 보기/안보기 的本地化字符串。
        /// </summary>
        internal static string btnShow {
            get {
                return ResourceManager.GetString("btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ---언어선택--- 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_01 {
            get {
                return ResourceManager.GetString("ClientText_aspx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 엑셀로 다운로드 받으시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_02 {
            get {
                return ResourceManager.GetString("ClientText_aspx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 엑셀로 데이터를 업로드 하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_03 {
            get {
                return ResourceManager.GetString("ClientText_aspx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업성공 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_04 {
            get {
                return ResourceManager.GetString("ClientText_aspx_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 한국어 이외의 데이터가 모두 초기화됩니다.\n진행하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_05 {
            get {
                return ResourceManager.GetString("ClientText_aspx_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 한국어 기준 데이터 초기화 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_06 {
            get {
                return ResourceManager.GetString("ClientText_aspx_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StandardLanguageID 를 선택해주세요 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_07 {
            get {
                return ResourceManager.GetString("ClientText_aspx_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파일을 선택해주세요. 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_08 {
            get {
                return ResourceManager.GetString("ClientText_aspx_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 테이블 초기화 실패 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_09 {
            get {
                return ResourceManager.GetString("ClientText_aspx_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 데이터 입력 실패 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_10 {
            get {
                return ResourceManager.GetString("ClientText_aspx_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 데이터 입력 완료 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_11 {
            get {
                return ResourceManager.GetString("ClientText_aspx_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파일 형식이 올바르지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_12 {
            get {
                return ResourceManager.GetString("ClientText_aspx_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 변경된 정보로 수정하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string COMMON_cfrm_01 {
            get {
                return ResourceManager.GetString("COMMON_cfrm_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 잘못된 접근입니다. 的本地化字符串。
        /// </summary>
        internal static string COMMON_mbox_01 {
            get {
                return ResourceManager.GetString("COMMON_mbox_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 예외발생 的本地化字符串。
        /// </summary>
        internal static string COMMON_mbox_02 {
            get {
                return ResourceManager.GetString("COMMON_mbox_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 처음 的本地化字符串。
        /// </summary>
        internal static string COMMON_page_txt_01 {
            get {
                return ResourceManager.GetString("COMMON_page_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이전 的本地化字符串。
        /// </summary>
        internal static string COMMON_page_txt_02 {
            get {
                return ResourceManager.GetString("COMMON_page_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 다음 的本地化字符串。
        /// </summary>
        internal static string COMMON_page_txt_03 {
            get {
                return ResourceManager.GetString("COMMON_page_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 끝 的本地化字符串。
        /// </summary>
        internal static string COMMON_page_txt_04 {
            get {
                return ResourceManager.GetString("COMMON_page_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 새 쿠폰 캠페인 등록하기 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_01 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 캠페인 정보 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_02 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 등록 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_03 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰길이 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_04 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰코드 헤더 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_05 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 앞자리에 들어갈 헤더 설정 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_06 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰공용사용여부 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_07 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_08 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (체크 시 1개의 동일한 쿠폰번호로 모든 캐릭터가 1회씩 사용 가능) 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_09 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰사용가능일시 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_10 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰사용가능여부 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_11 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 캠페인을 등록하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_12 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰발급수 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_13 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션 정보가 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_01 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임 서버가 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_02 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 캠페인을 수정하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_03 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 입력하신 내용을 다시 확인해주세요. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_04 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션 수정에 실패하였습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_05 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션 등록에 실패하였습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_06 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션 아이템 등록에 실패하였습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_07 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 등록에 실패하였습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_08 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션ID 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_09 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰코드 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_10 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 관리 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_01 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 캠페인 내역 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_02 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 캠페인 명 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_03 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 조회 기간 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_04 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 검색 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_05 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 검색 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_06 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 번호 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_07 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰수량 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_08 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용기간 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_09 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰타입 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_10 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰상태 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_11 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰번호 확인 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_12 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 열기 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_13 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 공통 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_cs_01 {
            get {
                return ResourceManager.GetString("CouponSystem_cs_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용안함 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_cs_02 {
            get {
                return ResourceManager.GetString("CouponSystem_cs_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이템명 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_01 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이템ID 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_02 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이템 갯수 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_03 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 캠페인 수정하기 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_04 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 목록 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_05 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 수정 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_06 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버그룹 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_01 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 서버그룹 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_02 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (그룹내) 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_03 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 자동추천대상 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_04 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 공개여부 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_05 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PK가능여부 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_06 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 타임존 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_07 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가상서버관리(전체) 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_08 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가상서버번호 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_09 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_10 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이름 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_11 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 표시번호 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_12 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 수정 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_13 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 서버ID 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_01 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 표시번호 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_02 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 서버명 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_03 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API 주소 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_04 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버주소 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_05 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버포트 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_06 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 접속유저수 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_07 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 점검여부 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_08 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 추천 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_09 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 상태 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_10 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 수정 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_11 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 추천 서버 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_01 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 숫자 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_02 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 정상 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_03 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 점검중 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_04 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 활성 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_05 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 비활성 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_06 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 추천서버 변경 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_07 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 등록하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_cs_cfrm_01 {
            get {
                return ResourceManager.GetString("GAMESLIST_cs_cfrm_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업실패(기존 추천 서버) 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_cs_mbox_01 {
            get {
                return ResourceManager.GetString("GAMESLIST_cs_mbox_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업실패(새 추천 서버) 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_cs_mbox_02 {
            get {
                return ResourceManager.GetString("GAMESLIST_cs_mbox_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영웅정보 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_01 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 직업ID 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_02 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가ID 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_03 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이름 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_04 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 레벨 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_05 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 경험치 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_06 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 전투력 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_07 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 골드 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_08 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 라크 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_09 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 귀속다이아 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_10 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIP포인트 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_11 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 체력 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_12 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 공적점수 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_13 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 착용날개 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_14 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개단계 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_15 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개레벨 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_16 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개경험치 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_17 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인장비강화 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_18 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인장비세련 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_19 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 무료즉시부활 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_20 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 유료부활 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_21 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 휴식시간 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_22 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 일일출석보상 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_23 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 일일접속시간 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_24 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 탈것장비재강화 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_25 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 경험치물약사용 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_26 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 착용탈것 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_27 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 무료소탕사용 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_28 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인퀘스트 번호 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_29 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 구입인벤토리슬롯수 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_30 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인장비(무기) 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_31 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인장비(방어구) 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_32 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이름튜토리얼 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_33 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 마지막로그인 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_34 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 마지막로그아웃 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_35 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 상태 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_36 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 등록시각 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_37 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GM여부 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_38 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 누적구매다이아 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_39 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 누적소비다이아 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_40 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 연속로그인 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_41 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 점령티어이름 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_42 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 점령티어 레벨 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_43 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 점령티어 경험치 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_44 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 별의정수 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_45 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영혼가루 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_46 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 구입한 창고 슬롯수 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_47 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 날개명칭 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_48 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사유 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_49 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 수정 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_50 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 처리내역 的本地化字符串。
        /// </summary>
        internal static string HeroInfo_aspx_51 {
            get {
                return ResourceManager.GetString("HeroInfo_aspx_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영웅관리 的本地化字符串。
        /// </summary>
        internal static string HeroList_01 {
            get {
                return ResourceManager.GetString("HeroList_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가상서버 的本地化字符串。
        /// </summary>
        internal static string HeroList_02 {
            get {
                return ResourceManager.GetString("HeroList_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 검색대상 的本地化字符串。
        /// </summary>
        internal static string HeroList_03 {
            get {
                return ResourceManager.GetString("HeroList_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 검색 的本地化字符串。
        /// </summary>
        internal static string HeroList_04 {
            get {
                return ResourceManager.GetString("HeroList_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영웅이름 的本地化字符串。
        /// </summary>
        internal static string HeroList_05 {
            get {
                return ResourceManager.GetString("HeroList_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영웅ID 的本地化字符串。
        /// </summary>
        internal static string HeroList_06 {
            get {
                return ResourceManager.GetString("HeroList_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 =가상서버선택= 的本地化字符串。
        /// </summary>
        internal static string HeroList_07 {
            get {
                return ResourceManager.GetString("HeroList_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 삭제됨 的本地化字符串。
        /// </summary>
        internal static string HeroList_08 {
            get {
                return ResourceManager.GetString("HeroList_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영웅ID 的本地化字符串。
        /// </summary>
        internal static string HeroList_tr_01 {
            get {
                return ResourceManager.GetString("HeroList_tr_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이름 的本地化字符串。
        /// </summary>
        internal static string HeroList_tr_02 {
            get {
                return ResourceManager.GetString("HeroList_tr_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 계정ID 的本地化字符串。
        /// </summary>
        internal static string HeroList_tr_03 {
            get {
                return ResourceManager.GetString("HeroList_tr_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 국가ID 的本地化字符串。
        /// </summary>
        internal static string HeroList_tr_04 {
            get {
                return ResourceManager.GetString("HeroList_tr_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 직업ID 的本地化字符串。
        /// </summary>
        internal static string HeroList_tr_05 {
            get {
                return ResourceManager.GetString("HeroList_tr_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 레벨 的本地化字符串。
        /// </summary>
        internal static string HeroList_tr_06 {
            get {
                return ResourceManager.GetString("HeroList_tr_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 삭제여부 的本地化字符串。
        /// </summary>
        internal static string HeroList_tr_07 {
            get {
                return ResourceManager.GetString("HeroList_tr_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 등록시각 的本地化字符串。
        /// </summary>
        internal static string HeroList_tr_08 {
            get {
                return ResourceManager.GetString("HeroList_tr_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 계정정보 的本地化字符串。
        /// </summary>
        internal static string Hero_aspx_01 {
            get {
                return ResourceManager.GetString("Hero_aspx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 수정 的本地化字符串。
        /// </summary>
        internal static string Hero_aspx_02 {
            get {
                return ResourceManager.GetString("Hero_aspx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 보유계정영웅 的本地化字符串。
        /// </summary>
        internal static string Hero_aspx_03 {
            get {
                return ResourceManager.GetString("Hero_aspx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 계정영웅 GM 이전 的本地化字符串。
        /// </summary>
        internal static string Hero_aspx_04 {
            get {
                return ResourceManager.GetString("Hero_aspx_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GM 닉네임 的本地化字符串。
        /// </summary>
        internal static string Hero_aspx_05 {
            get {
                return ResourceManager.GetString("Hero_aspx_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영웅정보 的本地化字符串。
        /// </summary>
        internal static string Hero_aspx_06 {
            get {
                return ResourceManager.GetString("Hero_aspx_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 인벤토리 的本地化字符串。
        /// </summary>
        internal static string Hero_aspx_07 {
            get {
                return ResourceManager.GetString("Hero_aspx_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메인퀘스트 的本地化字符串。
        /// </summary>
        internal static string Hero_aspx_08 {
            get {
                return ResourceManager.GetString("Hero_aspx_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 개발자 전용입니다. 的本地化字符串。
        /// </summary>
        internal static string Login_01 {
            get {
                return ResourceManager.GetString("Login_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 로그인 的本地化字符串。
        /// </summary>
        internal static string Login_02 {
            get {
                return ResourceManager.GetString("Login_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이디를 입력하세요. 的本地化字符串。
        /// </summary>
        internal static string Login_03 {
            get {
                return ResourceManager.GetString("Login_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 비밀번호를 입력하세요. 的本地化字符串。
        /// </summary>
        internal static string Login_04 {
            get {
                return ResourceManager.GetString("Login_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이디를 입력해주세요. 的本地化字符串。
        /// </summary>
        internal static string Login_05 {
            get {
                return ResourceManager.GetString("Login_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 비밀번호를 입력해주세요. 的本地化字符串。
        /// </summary>
        internal static string Login_06 {
            get {
                return ResourceManager.GetString("Login_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이디 또는 비밀번호가 올바르지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string Login_07 {
            get {
                return ResourceManager.GetString("Login_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 권한이 없습니다. 的本地化字符串。
        /// </summary>
        internal static string Master_Main_Cs_001 {
            get {
                return ResourceManager.GetString("Master_Main_Cs_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_01 {
            get {
                return ResourceManager.GetString("MenuUtil_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_01_001 {
            get {
                return ResourceManager.GetString("MenuUtil_01_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02 {
            get {
                return ResourceManager.GetString("MenuUtil_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영웅 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_001 {
            get {
                return ResourceManager.GetString("MenuUtil_02_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 어셋번들 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_002 {
            get {
                return ResourceManager.GetString("MenuUtil_02_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메뉴설정 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_003 {
            get {
                return ResourceManager.GetString("MenuUtil_02_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 우편 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_004 {
            get {
                return ResourceManager.GetString("MenuUtil_02_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 우편(전체) 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_005 {
            get {
                return ResourceManager.GetString("MenuUtil_02_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 개발 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_006 {
            get {
                return ResourceManager.GetString("MenuUtil_02_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 인게임 공지 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_007 {
            get {
                return ResourceManager.GetString("MenuUtil_02_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 접속자 우편발송 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_008 {
            get {
                return ResourceManager.GetString("MenuUtil_02_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 충전(구입상품관리) 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_009 {
            get {
                return ResourceManager.GetString("MenuUtil_02_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 다이아상점(한정상품) 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_010 {
            get {
                return ResourceManager.GetString("MenuUtil_02_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 설정 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03 {
            get {
                return ResourceManager.GetString("MenuUtil_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 시스템 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_001 {
            get {
                return ResourceManager.GetString("MenuUtil_03_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_002 {
            get {
                return ResourceManager.GetString("MenuUtil_03_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 언어 관리 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_003 {
            get {
                return ResourceManager.GetString("MenuUtil_03_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 화이트 IP 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_004 {
            get {
                return ResourceManager.GetString("MenuUtil_03_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임시스템 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_005 {
            get {
                return ResourceManager.GetString("MenuUtil_03_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버지역 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_006 {
            get {
                return ResourceManager.GetString("MenuUtil_03_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버그룹 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_007 {
            get {
                return ResourceManager.GetString("MenuUtil_03_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버 접속관리 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_008 {
            get {
                return ResourceManager.GetString("MenuUtil_03_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 관리 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_009 {
            get {
                return ResourceManager.GetString("MenuUtil_03_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 차단IP 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_010 {
            get {
                return ResourceManager.GetString("MenuUtil_03_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 공유하기 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_011 {
            get {
                return ResourceManager.GetString("MenuUtil_03_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 클라이언트 텍스트 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_012 {
            get {
                return ResourceManager.GetString("MenuUtil_03_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 도구 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_04 {
            get {
                return ResourceManager.GetString("MenuUtil_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 클라이언트 텍스트 확인 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_04_001 {
            get {
                return ResourceManager.GetString("MenuUtil_04_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logs 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_05 {
            get {
                return ResourceManager.GetString("MenuUtil_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 결제로그 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_05_001 {
            get {
                return ResourceManager.GetString("MenuUtil_05_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 번호 전체 확인 的本地化字符串。
        /// </summary>
        internal static string PopupCoupon_aspx_txt_01 {
            get {
                return ResourceManager.GetString("PopupCoupon_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 코드 的本地化字符串。
        /// </summary>
        internal static string PopupCoupon_aspx_txt_02 {
            get {
                return ResourceManager.GetString("PopupCoupon_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 닫기 的本地化字符串。
        /// </summary>
        internal static string PopupCoupon_aspx_txt_03 {
            get {
                return ResourceManager.GetString("PopupCoupon_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업실패 的本地化字符串。
        /// </summary>
        internal static string SENDMAIL_cs_mbox_03 {
            get {
                return ResourceManager.GetString("SENDMAIL_cs_mbox_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 로그아웃 的本地化字符串。
        /// </summary>
        internal static string UserControl_TopMenu_001 {
            get {
                return ResourceManager.GetString("UserControl_TopMenu_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자관리 的本地化字符串。
        /// </summary>
        internal static string UserList_01 {
            get {
                return ResourceManager.GetString("UserList_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 검색 的本地化字符串。
        /// </summary>
        internal static string UserList_02 {
            get {
                return ResourceManager.GetString("UserList_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게스트 사용자 생성 的本地化字符串。
        /// </summary>
        internal static string UserList_03 {
            get {
                return ResourceManager.GetString("UserList_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자를 등록하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string UserList_04 {
            get {
                return ResourceManager.GetString("UserList_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자ID [{0}] 검색결과 : {1}건 的本地化字符串。
        /// </summary>
        internal static string UserList_05 {
            get {
                return ResourceManager.GetString("UserList_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 처음 的本地化字符串。
        /// </summary>
        internal static string UserList_06 {
            get {
                return ResourceManager.GetString("UserList_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이전 的本地化字符串。
        /// </summary>
        internal static string UserList_07 {
            get {
                return ResourceManager.GetString("UserList_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 다음 的本地化字符串。
        /// </summary>
        internal static string UserList_08 {
            get {
                return ResourceManager.GetString("UserList_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 끝 的本地化字符串。
        /// </summary>
        internal static string UserList_09 {
            get {
                return ResourceManager.GetString("UserList_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 계정생성완료\\n{0} 的本地化字符串。
        /// </summary>
        internal static string UserList_10 {
            get {
                return ResourceManager.GetString("UserList_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게스트 的本地化字符串。
        /// </summary>
        internal static string UserList_11 {
            get {
                return ResourceManager.GetString("UserList_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 페이스북 的本地化字符串。
        /// </summary>
        internal static string UserList_12 {
            get {
                return ResourceManager.GetString("UserList_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 구글 的本地化字符串。
        /// </summary>
        internal static string UserList_13 {
            get {
                return ResourceManager.GetString("UserList_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 엔터메이트 的本地化字符串。
        /// </summary>
        internal static string UserList_14 {
            get {
                return ResourceManager.GetString("UserList_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 유효하지않음 的本地化字符串。
        /// </summary>
        internal static string UserList_15 {
            get {
                return ResourceManager.GetString("UserList_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 삭제 的本地化字符串。
        /// </summary>
        internal static string UserList_16 {
            get {
                return ResourceManager.GetString("UserList_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 정상 的本地化字符串。
        /// </summary>
        internal static string UserList_17 {
            get {
                return ResourceManager.GetString("UserList_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자ID 的本地化字符串。
        /// </summary>
        internal static string UserList_tr_01 {
            get {
                return ResourceManager.GetString("UserList_tr_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 비밀키 的本地化字符串。
        /// </summary>
        internal static string UserList_tr_02 {
            get {
                return ResourceManager.GetString("UserList_tr_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 엑세스키 的本地化字符串。
        /// </summary>
        internal static string UserList_tr_03 {
            get {
                return ResourceManager.GetString("UserList_tr_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 인증타입 的本地化字符串。
        /// </summary>
        internal static string UserList_tr_04 {
            get {
                return ResourceManager.GetString("UserList_tr_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 삭제여부 的本地化字符串。
        /// </summary>
        internal static string UserList_tr_05 {
            get {
                return ResourceManager.GetString("UserList_tr_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 등록시각 的本地化字符串。
        /// </summary>
        internal static string UserList_tr_06 {
            get {
                return ResourceManager.GetString("UserList_tr_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 엑세스토큰 的本地化字符串。
        /// </summary>
        internal static string UserList_tr_07 {
            get {
                return ResourceManager.GetString("UserList_tr_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 찾기 的本地化字符串。
        /// </summary>
        internal static string WBtnGMSearch {
            get {
                return ResourceManager.GetString("WBtnGMSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 계정영웅 이전 的本地化字符串。
        /// </summary>
        internal static string WBtnGMTrans {
            get {
                return ResourceManager.GetString("WBtnGMTrans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 계정영웅 회수 的本地化字符串。
        /// </summary>
        internal static string WBtnRecovery {
            get {
                return ResourceManager.GetString("WBtnRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 상태 的本地化字符串。
        /// </summary>
        internal static string WLtlDeleted {
            get {
                return ResourceManager.GetString("WLtlDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 최근로그인IP 的本地化字符串。
        /// </summary>
        internal static string WLtlLastLoginIp {
            get {
                return ResourceManager.GetString("WLtlLastLoginIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 최근로그인시각 的本地化字符串。
        /// </summary>
        internal static string WLtlLastLoginTime {
            get {
                return ResourceManager.GetString("WLtlLastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 등록시각 的本地化字符串。
        /// </summary>
        internal static string WLtlRegTime {
            get {
                return ResourceManager.GetString("WLtlRegTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자ID 的本地化字符串。
        /// </summary>
        internal static string WLtlUserId {
            get {
                return ResourceManager.GetString("WLtlUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIP보상내역 的本地化字符串。
        /// </summary>
        internal static string WLtlVipReward {
            get {
                return ResourceManager.GetString("WLtlVipReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가상게임서버ID 的本地化字符串。
        /// </summary>
        internal static string WLtlVirtualGameServerId {
            get {
                return ResourceManager.GetString("WLtlVirtualGameServerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 기본비귀속다이아 的本地化字符串。
        /// </summary>
        internal static string WTxtBaseUnOwnDia {
            get {
                return ResourceManager.GetString("WTxtBaseUnOwnDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 보너스비귀속다이아 的本地化字符串。
        /// </summary>
        internal static string WTxtBonusUnOwnDia {
            get {
                return ResourceManager.GetString("WTxtBonusUnOwnDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VIP포인트 的本地化字符串。
        /// </summary>
        internal static string WTxtVipPoint {
            get {
                return ResourceManager.GetString("WTxtVipPoint", resourceCulture);
            }
        }
    }
}
