//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResLang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCHfD_cs_txt_05 {
            get {
                return ResourceManager.GetString("ACCHfD_cs_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ACCHfD_cs_txt_06 {
            get {
                return ResourceManager.GetString("ACCHfD_cs_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이름을 입력해주세요. 的本地化字符串。
        /// </summary>
        internal static string ACCHINFO_cs_txt_06 {
            get {
                return ResourceManager.GetString("ACCHINFO_cs_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업성공 的本地化字符串。
        /// </summary>
        internal static string ACCHRE_cs_mbox_02 {
            get {
                return ResourceManager.GetString("ACCHRE_cs_mbox_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ---언어선택--- 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_01 {
            get {
                return ResourceManager.GetString("ClientText_aspx_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 엑셀로 다운로드 받으시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_02 {
            get {
                return ResourceManager.GetString("ClientText_aspx_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 엑셀로 데이터를 업로드 하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_03 {
            get {
                return ResourceManager.GetString("ClientText_aspx_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업성공 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_04 {
            get {
                return ResourceManager.GetString("ClientText_aspx_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 한국어 이외의 데이터가 모두 초기화됩니다.\n진행하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_05 {
            get {
                return ResourceManager.GetString("ClientText_aspx_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 한국어 기준 데이터 초기화 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_06 {
            get {
                return ResourceManager.GetString("ClientText_aspx_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StandardLanguageID 를 선택해주세요 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_07 {
            get {
                return ResourceManager.GetString("ClientText_aspx_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파일을 선택해주세요. 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_08 {
            get {
                return ResourceManager.GetString("ClientText_aspx_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 테이블 초기화 실패 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_09 {
            get {
                return ResourceManager.GetString("ClientText_aspx_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 데이터 입력 실패 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_10 {
            get {
                return ResourceManager.GetString("ClientText_aspx_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 데이터 입력 완료 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_11 {
            get {
                return ResourceManager.GetString("ClientText_aspx_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 파일 형식이 올바르지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string ClientText_aspx_12 {
            get {
                return ResourceManager.GetString("ClientText_aspx_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 변경된 정보로 수정하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string COMMON_cfrm_01 {
            get {
                return ResourceManager.GetString("COMMON_cfrm_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 잘못된 접근입니다. 的本地化字符串。
        /// </summary>
        internal static string COMMON_mbox_01 {
            get {
                return ResourceManager.GetString("COMMON_mbox_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 예외발생 的本地化字符串。
        /// </summary>
        internal static string COMMON_mbox_02 {
            get {
                return ResourceManager.GetString("COMMON_mbox_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 처음 的本地化字符串。
        /// </summary>
        internal static string COMMON_page_txt_01 {
            get {
                return ResourceManager.GetString("COMMON_page_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이전 的本地化字符串。
        /// </summary>
        internal static string COMMON_page_txt_02 {
            get {
                return ResourceManager.GetString("COMMON_page_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 다음 的本地化字符串。
        /// </summary>
        internal static string COMMON_page_txt_03 {
            get {
                return ResourceManager.GetString("COMMON_page_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 끝 的本地化字符串。
        /// </summary>
        internal static string COMMON_page_txt_04 {
            get {
                return ResourceManager.GetString("COMMON_page_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 새 쿠폰 캠페인 등록하기 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_01 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 캠페인 정보 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_02 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 등록 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_03 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰길이 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_04 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰코드 헤더 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_05 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 앞자리에 들어갈 헤더 설정 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_06 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰공용사용여부 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_07 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_08 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (체크 시 1개의 동일한 쿠폰번호로 모든 캐릭터가 1회씩 사용 가능) 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_09 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰사용가능일시 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_10 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰사용가능여부 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_11 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 캠페인을 등록하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_12 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰발급수 的本地化字符串。
        /// </summary>
        internal static string CouponAdd_aspx_txt_13 {
            get {
                return ResourceManager.GetString("CouponAdd_aspx_txt_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션 정보가 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_01 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임 서버가 존재하지 않습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_02 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 캠페인을 수정하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_03 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 입력하신 내용을 다시 확인해주세요. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_04 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션 수정에 실패하였습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_05 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션 등록에 실패하였습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_06 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션 아이템 등록에 실패하였습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_07 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 등록에 실패하였습니다. 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_08 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 프로모션ID 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_09 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰코드 的本地化字符串。
        /// </summary>
        internal static string CouponPopup_cs_txt_10 {
            get {
                return ResourceManager.GetString("CouponPopup_cs_txt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 관리 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_01 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 캠페인 내역 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_02 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 캠페인 명 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_03 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 조회 기간 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_04 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 검색 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_05 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 검색 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_06 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 번호 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_07 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰수량 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_08 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용기간 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_09 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰타입 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_10 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰상태 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_11 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰번호 확인 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_12 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 열기 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_aspx_txt_13 {
            get {
                return ResourceManager.GetString("CouponSystem_aspx_txt_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 공통 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_cs_01 {
            get {
                return ResourceManager.GetString("CouponSystem_cs_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용안함 的本地化字符串。
        /// </summary>
        internal static string CouponSystem_cs_02 {
            get {
                return ResourceManager.GetString("CouponSystem_cs_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이템명 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_01 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이템ID 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_02 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이템 갯수 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_03 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 캠페인 수정하기 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_04 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 목록 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_05 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 수정 的本地化字符串。
        /// </summary>
        internal static string CouponUpdate_aspx_txt_06 {
            get {
                return ResourceManager.GetString("CouponUpdate_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버그룹 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_01 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 서버그룹 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_02 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (그룹내) 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_03 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 자동추천대상 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_04 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 공개여부 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_05 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PK가능여부 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_06 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 타임존 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_07 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가상서버관리(전체) 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_08 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 가상서버번호 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_09 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_10 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 이름 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_11 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 표시번호 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_12 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 수정 的本地化字符串。
        /// </summary>
        internal static string GameServerList_aspx_txt_13 {
            get {
                return ResourceManager.GetString("GameServerList_aspx_txt_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 서버ID 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_01 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 표시번호 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_02 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 서버명 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_03 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API 주소 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_04 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버주소 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_05 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버포트 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_06 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 접속유저수 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_07 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 점검여부 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_08 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 추천 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_09 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 상태 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_10 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 수정 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_th_11 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_th_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 추천 서버 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_01 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 숫자 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_02 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 정상 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_03 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 점검중 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_04 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 활성 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_05 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 비활성 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_06 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 추천서버 변경 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_aspx_txt_07 {
            get {
                return ResourceManager.GetString("GAMESLIST_aspx_txt_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 등록하시겠습니까? 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_cs_cfrm_01 {
            get {
                return ResourceManager.GetString("GAMESLIST_cs_cfrm_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업실패(기존 추천 서버) 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_cs_mbox_01 {
            get {
                return ResourceManager.GetString("GAMESLIST_cs_mbox_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업실패(새 추천 서버) 的本地化字符串。
        /// </summary>
        internal static string GAMESLIST_cs_mbox_02 {
            get {
                return ResourceManager.GetString("GAMESLIST_cs_mbox_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 개발자 전용입니다. 的本地化字符串。
        /// </summary>
        internal static string Login_01 {
            get {
                return ResourceManager.GetString("Login_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 로그인 的本地化字符串。
        /// </summary>
        internal static string Login_02 {
            get {
                return ResourceManager.GetString("Login_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 아이디를 입력하세요. 的本地化字符串。
        /// </summary>
        internal static string Login_03 {
            get {
                return ResourceManager.GetString("Login_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 비밀번호를 입력하세요. 的本地化字符串。
        /// </summary>
        internal static string Login_04 {
            get {
                return ResourceManager.GetString("Login_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 권한이 없습니다. 的本地化字符串。
        /// </summary>
        internal static string Master_Main_Cs_001 {
            get {
                return ResourceManager.GetString("Master_Main_Cs_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_01 {
            get {
                return ResourceManager.GetString("MenuUtil_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 사용자 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_01_001 {
            get {
                return ResourceManager.GetString("MenuUtil_01_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02 {
            get {
                return ResourceManager.GetString("MenuUtil_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 영웅 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_001 {
            get {
                return ResourceManager.GetString("MenuUtil_02_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 어셋번들 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_002 {
            get {
                return ResourceManager.GetString("MenuUtil_02_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 메뉴설정 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_003 {
            get {
                return ResourceManager.GetString("MenuUtil_02_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 우편 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_004 {
            get {
                return ResourceManager.GetString("MenuUtil_02_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 우편(전체) 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_005 {
            get {
                return ResourceManager.GetString("MenuUtil_02_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 개발 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_006 {
            get {
                return ResourceManager.GetString("MenuUtil_02_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 인게임 공지 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_007 {
            get {
                return ResourceManager.GetString("MenuUtil_02_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 접속자 우편발송 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_008 {
            get {
                return ResourceManager.GetString("MenuUtil_02_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 충전(구입상품관리) 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_009 {
            get {
                return ResourceManager.GetString("MenuUtil_02_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 다이아상점(한정상품) 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_02_010 {
            get {
                return ResourceManager.GetString("MenuUtil_02_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 설정 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03 {
            get {
                return ResourceManager.GetString("MenuUtil_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 시스템 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_001 {
            get {
                return ResourceManager.GetString("MenuUtil_03_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_002 {
            get {
                return ResourceManager.GetString("MenuUtil_03_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 언어 관리 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_003 {
            get {
                return ResourceManager.GetString("MenuUtil_03_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 화이트 IP 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_004 {
            get {
                return ResourceManager.GetString("MenuUtil_03_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임시스템 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_005 {
            get {
                return ResourceManager.GetString("MenuUtil_03_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버지역 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_006 {
            get {
                return ResourceManager.GetString("MenuUtil_03_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버그룹 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_007 {
            get {
                return ResourceManager.GetString("MenuUtil_03_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 게임서버 접속관리 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_008 {
            get {
                return ResourceManager.GetString("MenuUtil_03_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 관리 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_009 {
            get {
                return ResourceManager.GetString("MenuUtil_03_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 차단IP 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_010 {
            get {
                return ResourceManager.GetString("MenuUtil_03_010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 공유하기 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_011 {
            get {
                return ResourceManager.GetString("MenuUtil_03_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 클라이언트 텍스트 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_03_012 {
            get {
                return ResourceManager.GetString("MenuUtil_03_012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 도구 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_04 {
            get {
                return ResourceManager.GetString("MenuUtil_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 클라이언트 텍스트 확인 的本地化字符串。
        /// </summary>
        internal static string MenuUtil_04_001 {
            get {
                return ResourceManager.GetString("MenuUtil_04_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 번호 전체 확인 的本地化字符串。
        /// </summary>
        internal static string PopupCoupon_aspx_txt_01 {
            get {
                return ResourceManager.GetString("PopupCoupon_aspx_txt_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 쿠폰 코드 的本地化字符串。
        /// </summary>
        internal static string PopupCoupon_aspx_txt_02 {
            get {
                return ResourceManager.GetString("PopupCoupon_aspx_txt_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 닫기 的本地化字符串。
        /// </summary>
        internal static string PopupCoupon_aspx_txt_03 {
            get {
                return ResourceManager.GetString("PopupCoupon_aspx_txt_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 작업실패 的本地化字符串。
        /// </summary>
        internal static string SENDMAIL_cs_mbox_03 {
            get {
                return ResourceManager.GetString("SENDMAIL_cs_mbox_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 로그아웃 的本地化字符串。
        /// </summary>
        internal static string UserControl_TopMenu_001 {
            get {
                return ResourceManager.GetString("UserControl_TopMenu_001", resourceCulture);
            }
        }
    }
}
